apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-app
  labels:
    app: custom-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: custom-app
  template:
    metadata:
      labels:
        app: custom-app
    spec:
      containers:
        - name: custom-app
          image: 730335384723.dkr.ecr.ap-south-1.amazonaws.com/hybrid:v_1e737fc_2025_03_13_20_02
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: custom-app-service
spec:
  selector:
    app: custom-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP  # Change to LoadBalancer or NodePort if needed
